"""Jinja2 filters and tests - auto-generated from Ansible source.

DO NOT EDIT. Regenerate with: python tools/extract_schema.py
"""

from dataclasses import dataclass
from typing import Optional


@dataclass(frozen=True, slots=True)
class JinjaFilter:
    """A Jinja2 filter available in Ansible templates."""
    fqcn: str
    short_name: str
    source: str
    aliases: tuple[str, ...] = ()


@dataclass(frozen=True, slots=True)
class JinjaTest:
    """A Jinja2 test available in Ansible templates."""
    fqcn: str
    short_name: str
    source: str
    aliases: tuple[str, ...] = ()


FILTERS: dict[str, JinjaFilter] = {
    'b64decode': JinjaFilter('ansible.builtin.b64decode', 'b64decode', 'ansible', ('ansible.builtin.b64decode',)),
    'b64encode': JinjaFilter('ansible.builtin.b64encode', 'b64encode', 'ansible', ('ansible.builtin.b64encode',)),
    'basename': JinjaFilter('ansible.builtin.basename', 'basename', 'ansible', ('ansible.builtin.basename',)),
    'bool': JinjaFilter('ansible.builtin.bool', 'bool', 'ansible', ('ansible.builtin.bool',)),
    'checksum': JinjaFilter('ansible.builtin.checksum', 'checksum', 'ansible', ('ansible.builtin.checksum',)),
    'combinations': JinjaFilter('ansible.builtin.combinations', 'combinations', 'ansible', ('ansible.builtin.combinations',)),
    'combine': JinjaFilter('ansible.builtin.combine', 'combine', 'ansible', ('ansible.builtin.combine',)),
    'comment': JinjaFilter('ansible.builtin.comment', 'comment', 'ansible', ('ansible.builtin.comment',)),
    'commonpath': JinjaFilter('ansible.builtin.commonpath', 'commonpath', 'ansible', ('ansible.builtin.commonpath',)),
    'd': JinjaFilter('ansible.builtin.d', 'd', 'ansible', ('ansible.builtin.d',)),
    'default': JinjaFilter('ansible.builtin.default', 'default', 'ansible', ('ansible.builtin.default',)),
    'dict2items': JinjaFilter('ansible.builtin.dict2items', 'dict2items', 'ansible', ('ansible.builtin.dict2items',)),
    'difference': JinjaFilter('ansible.builtin.difference', 'difference', 'ansible', ('ansible.builtin.difference',)),
    'dirname': JinjaFilter('ansible.builtin.dirname', 'dirname', 'ansible', ('ansible.builtin.dirname',)),
    'expanduser': JinjaFilter('ansible.builtin.expanduser', 'expanduser', 'ansible', ('ansible.builtin.expanduser',)),
    'expandvars': JinjaFilter('ansible.builtin.expandvars', 'expandvars', 'ansible', ('ansible.builtin.expandvars',)),
    'extract': JinjaFilter('ansible.builtin.extract', 'extract', 'ansible', ('ansible.builtin.extract',)),
    'fileglob': JinjaFilter('ansible.builtin.fileglob', 'fileglob', 'ansible', ('ansible.builtin.fileglob',)),
    'flatten': JinjaFilter('ansible.builtin.flatten', 'flatten', 'ansible', ('ansible.builtin.flatten',)),
    'from_json': JinjaFilter('ansible.builtin.from_json', 'from_json', 'ansible', ('ansible.builtin.from_json',)),
    'from_yaml': JinjaFilter('ansible.builtin.from_yaml', 'from_yaml', 'ansible', ('ansible.builtin.from_yaml',)),
    'from_yaml_all': JinjaFilter('ansible.builtin.from_yaml_all', 'from_yaml_all', 'ansible', ('ansible.builtin.from_yaml_all',)),
    'groupby': JinjaFilter('ansible.builtin.groupby', 'groupby', 'ansible', ('ansible.builtin.groupby',)),
    'hash': JinjaFilter('ansible.builtin.hash', 'hash', 'ansible', ('ansible.builtin.hash',)),
    'human_readable': JinjaFilter('ansible.builtin.human_readable', 'human_readable', 'ansible', ('ansible.builtin.human_readable',)),
    'human_to_bytes': JinjaFilter('ansible.builtin.human_to_bytes', 'human_to_bytes', 'ansible', ('ansible.builtin.human_to_bytes',)),
    'intersect': JinjaFilter('ansible.builtin.intersect', 'intersect', 'ansible', ('ansible.builtin.intersect',)),
    'items2dict': JinjaFilter('ansible.builtin.items2dict', 'items2dict', 'ansible', ('ansible.builtin.items2dict',)),
    'log': JinjaFilter('ansible.builtin.log', 'log', 'ansible', ('ansible.builtin.log',)),
    'mandatory': JinjaFilter('ansible.builtin.mandatory', 'mandatory', 'ansible', ('ansible.builtin.mandatory',)),
    'map': JinjaFilter('ansible.builtin.map', 'map', 'ansible', ('ansible.builtin.map',)),
    'md5': JinjaFilter('ansible.builtin.md5', 'md5', 'ansible', ('ansible.builtin.md5',)),
    'normpath': JinjaFilter('ansible.builtin.normpath', 'normpath', 'ansible', ('ansible.builtin.normpath',)),
    'password_hash': JinjaFilter('ansible.builtin.password_hash', 'password_hash', 'ansible', ('ansible.builtin.password_hash',)),
    'path_join': JinjaFilter('ansible.builtin.path_join', 'path_join', 'ansible', ('ansible.builtin.path_join',)),
    'permutations': JinjaFilter('ansible.builtin.permutations', 'permutations', 'ansible', ('ansible.builtin.permutations',)),
    'pow': JinjaFilter('ansible.builtin.pow', 'pow', 'ansible', ('ansible.builtin.pow',)),
    'product': JinjaFilter('ansible.builtin.product', 'product', 'ansible', ('ansible.builtin.product',)),
    'quote': JinjaFilter('ansible.builtin.quote', 'quote', 'ansible', ('ansible.builtin.quote',)),
    'random': JinjaFilter('ansible.builtin.random', 'random', 'ansible', ('ansible.builtin.random',)),
    'realpath': JinjaFilter('ansible.builtin.realpath', 'realpath', 'ansible', ('ansible.builtin.realpath',)),
    'regex_escape': JinjaFilter('ansible.builtin.regex_escape', 'regex_escape', 'ansible', ('ansible.builtin.regex_escape',)),
    'regex_findall': JinjaFilter('ansible.builtin.regex_findall', 'regex_findall', 'ansible', ('ansible.builtin.regex_findall',)),
    'regex_replace': JinjaFilter('ansible.builtin.regex_replace', 'regex_replace', 'ansible', ('ansible.builtin.regex_replace',)),
    'regex_search': JinjaFilter('ansible.builtin.regex_search', 'regex_search', 'ansible', ('ansible.builtin.regex_search',)),
    'reject': JinjaFilter('ansible.builtin.reject', 'reject', 'ansible', ('ansible.builtin.reject',)),
    'rejectattr': JinjaFilter('ansible.builtin.rejectattr', 'rejectattr', 'ansible', ('ansible.builtin.rejectattr',)),
    'rekey_on_member': JinjaFilter('ansible.builtin.rekey_on_member', 'rekey_on_member', 'ansible', ('ansible.builtin.rekey_on_member',)),
    'relpath': JinjaFilter('ansible.builtin.relpath', 'relpath', 'ansible', ('ansible.builtin.relpath',)),
    'root': JinjaFilter('ansible.builtin.root', 'root', 'ansible', ('ansible.builtin.root',)),
    'select': JinjaFilter('ansible.builtin.select', 'select', 'ansible', ('ansible.builtin.select',)),
    'selectattr': JinjaFilter('ansible.builtin.selectattr', 'selectattr', 'ansible', ('ansible.builtin.selectattr',)),
    'sha1': JinjaFilter('ansible.builtin.sha1', 'sha1', 'ansible', ('ansible.builtin.sha1',)),
    'shuffle': JinjaFilter('ansible.builtin.shuffle', 'shuffle', 'ansible', ('ansible.builtin.shuffle',)),
    'split': JinjaFilter('ansible.builtin.split', 'split', 'ansible', ('ansible.builtin.split',)),
    'splitext': JinjaFilter('ansible.builtin.splitext', 'splitext', 'ansible', ('ansible.builtin.splitext',)),
    'strftime': JinjaFilter('ansible.builtin.strftime', 'strftime', 'ansible', ('ansible.builtin.strftime',)),
    'subelements': JinjaFilter('ansible.builtin.subelements', 'subelements', 'ansible', ('ansible.builtin.subelements',)),
    'symmetric_difference': JinjaFilter('ansible.builtin.symmetric_difference', 'symmetric_difference', 'ansible', ('ansible.builtin.symmetric_difference',)),
    'ternary': JinjaFilter('ansible.builtin.ternary', 'ternary', 'ansible', ('ansible.builtin.ternary',)),
    'to_datetime': JinjaFilter('ansible.builtin.to_datetime', 'to_datetime', 'ansible', ('ansible.builtin.to_datetime',)),
    'to_json': JinjaFilter('ansible.builtin.to_json', 'to_json', 'ansible', ('ansible.builtin.to_json',)),
    'to_nice_json': JinjaFilter('ansible.builtin.to_nice_json', 'to_nice_json', 'ansible', ('ansible.builtin.to_nice_json',)),
    'to_nice_yaml': JinjaFilter('ansible.builtin.to_nice_yaml', 'to_nice_yaml', 'ansible', ('ansible.builtin.to_nice_yaml',)),
    'to_uuid': JinjaFilter('ansible.builtin.to_uuid', 'to_uuid', 'ansible', ('ansible.builtin.to_uuid',)),
    'to_yaml': JinjaFilter('ansible.builtin.to_yaml', 'to_yaml', 'ansible', ('ansible.builtin.to_yaml',)),
    'type_debug': JinjaFilter('ansible.builtin.type_debug', 'type_debug', 'ansible', ('ansible.builtin.type_debug',)),
    'union': JinjaFilter('ansible.builtin.union', 'union', 'ansible', ('ansible.builtin.union',)),
    'unique': JinjaFilter('ansible.builtin.unique', 'unique', 'ansible', ('ansible.builtin.unique',)),
    'unvault': JinjaFilter('ansible.builtin.unvault', 'unvault', 'ansible', ('ansible.builtin.unvault',)),
    'urldecode': JinjaFilter('ansible.builtin.urldecode', 'urldecode', 'ansible', ('ansible.builtin.urldecode',)),
    'urlsplit': JinjaFilter('ansible.builtin.urlsplit', 'urlsplit', 'ansible', ('ansible.builtin.urlsplit',)),
    'vault': JinjaFilter('ansible.builtin.vault', 'vault', 'ansible', ('ansible.builtin.vault',)),
    'win_basename': JinjaFilter('ansible.builtin.win_basename', 'win_basename', 'ansible', ('ansible.builtin.win_basename',)),
    'win_dirname': JinjaFilter('ansible.builtin.win_dirname', 'win_dirname', 'ansible', ('ansible.builtin.win_dirname',)),
    'win_splitdrive': JinjaFilter('ansible.builtin.win_splitdrive', 'win_splitdrive', 'ansible', ('ansible.builtin.win_splitdrive',)),
    'zip': JinjaFilter('ansible.builtin.zip', 'zip', 'ansible', ('ansible.builtin.zip',)),
    'zip_longest': JinjaFilter('ansible.builtin.zip_longest', 'zip_longest', 'ansible', ('ansible.builtin.zip_longest',)),
    'abs': JinjaFilter('jinja2.abs', 'abs', 'jinja2_builtin', ()),
    'attr': JinjaFilter('jinja2.attr', 'attr', 'jinja2_builtin', ()),
    'batch': JinjaFilter('jinja2.batch', 'batch', 'jinja2_builtin', ()),
    'capitalize': JinjaFilter('jinja2.capitalize', 'capitalize', 'jinja2_builtin', ()),
    'center': JinjaFilter('jinja2.center', 'center', 'jinja2_builtin', ()),
    'count': JinjaFilter('jinja2.count', 'count', 'jinja2_builtin', ()),
    'dictsort': JinjaFilter('jinja2.dictsort', 'dictsort', 'jinja2_builtin', ()),
    'e': JinjaFilter('jinja2.e', 'e', 'jinja2_builtin', ()),
    'escape': JinjaFilter('jinja2.escape', 'escape', 'jinja2_builtin', ()),
    'filesizeformat': JinjaFilter('jinja2.filesizeformat', 'filesizeformat', 'jinja2_builtin', ()),
    'first': JinjaFilter('jinja2.first', 'first', 'jinja2_builtin', ()),
    'float': JinjaFilter('jinja2.float', 'float', 'jinja2_builtin', ()),
    'forceescape': JinjaFilter('jinja2.forceescape', 'forceescape', 'jinja2_builtin', ()),
    'format': JinjaFilter('jinja2.format', 'format', 'jinja2_builtin', ()),
    'indent': JinjaFilter('jinja2.indent', 'indent', 'jinja2_builtin', ()),
    'int': JinjaFilter('jinja2.int', 'int', 'jinja2_builtin', ()),
    'items': JinjaFilter('jinja2.items', 'items', 'jinja2_builtin', ()),
    'join': JinjaFilter('jinja2.join', 'join', 'jinja2_builtin', ()),
    'last': JinjaFilter('jinja2.last', 'last', 'jinja2_builtin', ()),
    'length': JinjaFilter('jinja2.length', 'length', 'jinja2_builtin', ()),
    'list': JinjaFilter('jinja2.list', 'list', 'jinja2_builtin', ()),
    'lower': JinjaFilter('jinja2.lower', 'lower', 'jinja2_builtin', ()),
    'max': JinjaFilter('jinja2.max', 'max', 'jinja2_builtin', ()),
    'min': JinjaFilter('jinja2.min', 'min', 'jinja2_builtin', ()),
    'pprint': JinjaFilter('jinja2.pprint', 'pprint', 'jinja2_builtin', ()),
    'replace': JinjaFilter('jinja2.replace', 'replace', 'jinja2_builtin', ()),
    'reverse': JinjaFilter('jinja2.reverse', 'reverse', 'jinja2_builtin', ()),
    'round': JinjaFilter('jinja2.round', 'round', 'jinja2_builtin', ()),
    'safe': JinjaFilter('jinja2.safe', 'safe', 'jinja2_builtin', ()),
    'slice': JinjaFilter('jinja2.slice', 'slice', 'jinja2_builtin', ()),
    'sort': JinjaFilter('jinja2.sort', 'sort', 'jinja2_builtin', ()),
    'string': JinjaFilter('jinja2.string', 'string', 'jinja2_builtin', ()),
    'striptags': JinjaFilter('jinja2.striptags', 'striptags', 'jinja2_builtin', ()),
    'sum': JinjaFilter('jinja2.sum', 'sum', 'jinja2_builtin', ()),
    'title': JinjaFilter('jinja2.title', 'title', 'jinja2_builtin', ()),
    'tojson': JinjaFilter('jinja2.tojson', 'tojson', 'jinja2_builtin', ()),
    'trim': JinjaFilter('jinja2.trim', 'trim', 'jinja2_builtin', ()),
    'truncate': JinjaFilter('jinja2.truncate', 'truncate', 'jinja2_builtin', ()),
    'upper': JinjaFilter('jinja2.upper', 'upper', 'jinja2_builtin', ()),
    'urlencode': JinjaFilter('jinja2.urlencode', 'urlencode', 'jinja2_builtin', ()),
    'urlize': JinjaFilter('jinja2.urlize', 'urlize', 'jinja2_builtin', ()),
    'wordcount': JinjaFilter('jinja2.wordcount', 'wordcount', 'jinja2_builtin', ()),
    'wordwrap': JinjaFilter('jinja2.wordwrap', 'wordwrap', 'jinja2_builtin', ()),
    'xmlattr': JinjaFilter('jinja2.xmlattr', 'xmlattr', 'jinja2_builtin', ()),
}

TESTS: dict[str, JinjaTest] = {
    'abs': JinjaTest('ansible.builtin.abs', 'abs', 'ansible', ('ansible.builtin.abs',)),
    'all': JinjaTest('ansible.builtin.all', 'all', 'ansible', ('ansible.builtin.all',)),
    'any': JinjaTest('ansible.builtin.any', 'any', 'ansible', ('ansible.builtin.any',)),
    'change': JinjaTest('ansible.builtin.change', 'change', 'ansible', ('ansible.builtin.change',)),
    'changed': JinjaTest('ansible.builtin.changed', 'changed', 'ansible', ('ansible.builtin.changed',)),
    'contains': JinjaTest('ansible.builtin.contains', 'contains', 'ansible', ('ansible.builtin.contains',)),
    'defined': JinjaTest('ansible.builtin.defined', 'defined', 'ansible', ('ansible.builtin.defined',)),
    'directory': JinjaTest('ansible.builtin.directory', 'directory', 'ansible', ('ansible.builtin.directory',)),
    'exists': JinjaTest('ansible.builtin.exists', 'exists', 'ansible', ('ansible.builtin.exists',)),
    'failed': JinjaTest('ansible.builtin.failed', 'failed', 'ansible', ('ansible.builtin.failed',)),
    'failure': JinjaTest('ansible.builtin.failure', 'failure', 'ansible', ('ansible.builtin.failure',)),
    'falsy': JinjaTest('ansible.builtin.falsy', 'falsy', 'ansible', ('ansible.builtin.falsy',)),
    'file': JinjaTest('ansible.builtin.file', 'file', 'ansible', ('ansible.builtin.file',)),
    'finished': JinjaTest('ansible.builtin.finished', 'finished', 'ansible', ('ansible.builtin.finished',)),
    'is_abs': JinjaTest('ansible.builtin.is_abs', 'is_abs', 'ansible', ('ansible.builtin.is_abs',)),
    'is_dir': JinjaTest('ansible.builtin.is_dir', 'is_dir', 'ansible', ('ansible.builtin.is_dir',)),
    'is_file': JinjaTest('ansible.builtin.is_file', 'is_file', 'ansible', ('ansible.builtin.is_file',)),
    'is_link': JinjaTest('ansible.builtin.is_link', 'is_link', 'ansible', ('ansible.builtin.is_link',)),
    'is_mount': JinjaTest('ansible.builtin.is_mount', 'is_mount', 'ansible', ('ansible.builtin.is_mount',)),
    'is_same_file': JinjaTest('ansible.builtin.is_same_file', 'is_same_file', 'ansible', ('ansible.builtin.is_same_file',)),
    'isnan': JinjaTest('ansible.builtin.isnan', 'isnan', 'ansible', ('ansible.builtin.isnan',)),
    'issubset': JinjaTest('ansible.builtin.issubset', 'issubset', 'ansible', ('ansible.builtin.issubset',)),
    'issuperset': JinjaTest('ansible.builtin.issuperset', 'issuperset', 'ansible', ('ansible.builtin.issuperset',)),
    'link': JinjaTest('ansible.builtin.link', 'link', 'ansible', ('ansible.builtin.link',)),
    'link_exists': JinjaTest('ansible.builtin.link_exists', 'link_exists', 'ansible', ('ansible.builtin.link_exists',)),
    'match': JinjaTest('ansible.builtin.match', 'match', 'ansible', ('ansible.builtin.match',)),
    'mount': JinjaTest('ansible.builtin.mount', 'mount', 'ansible', ('ansible.builtin.mount',)),
    'nan': JinjaTest('ansible.builtin.nan', 'nan', 'ansible', ('ansible.builtin.nan',)),
    'reachable': JinjaTest('ansible.builtin.reachable', 'reachable', 'ansible', ('ansible.builtin.reachable',)),
    'regex': JinjaTest('ansible.builtin.regex', 'regex', 'ansible', ('ansible.builtin.regex',)),
    'same_file': JinjaTest('ansible.builtin.same_file', 'same_file', 'ansible', ('ansible.builtin.same_file',)),
    'search': JinjaTest('ansible.builtin.search', 'search', 'ansible', ('ansible.builtin.search',)),
    'skip': JinjaTest('ansible.builtin.skip', 'skip', 'ansible', ('ansible.builtin.skip',)),
    'skipped': JinjaTest('ansible.builtin.skipped', 'skipped', 'ansible', ('ansible.builtin.skipped',)),
    'started': JinjaTest('ansible.builtin.started', 'started', 'ansible', ('ansible.builtin.started',)),
    'subset': JinjaTest('ansible.builtin.subset', 'subset', 'ansible', ('ansible.builtin.subset',)),
    'succeeded': JinjaTest('ansible.builtin.succeeded', 'succeeded', 'ansible', ('ansible.builtin.succeeded',)),
    'success': JinjaTest('ansible.builtin.success', 'success', 'ansible', ('ansible.builtin.success',)),
    'successful': JinjaTest('ansible.builtin.successful', 'successful', 'ansible', ('ansible.builtin.successful',)),
    'superset': JinjaTest('ansible.builtin.superset', 'superset', 'ansible', ('ansible.builtin.superset',)),
    'timedout': JinjaTest('ansible.builtin.timedout', 'timedout', 'ansible', ('ansible.builtin.timedout',)),
    'truthy': JinjaTest('ansible.builtin.truthy', 'truthy', 'ansible', ('ansible.builtin.truthy',)),
    'undefined': JinjaTest('ansible.builtin.undefined', 'undefined', 'ansible', ('ansible.builtin.undefined',)),
    'unreachable': JinjaTest('ansible.builtin.unreachable', 'unreachable', 'ansible', ('ansible.builtin.unreachable',)),
    'uri': JinjaTest('ansible.builtin.uri', 'uri', 'ansible', ('ansible.builtin.uri',)),
    'url': JinjaTest('ansible.builtin.url', 'url', 'ansible', ('ansible.builtin.url',)),
    'urn': JinjaTest('ansible.builtin.urn', 'urn', 'ansible', ('ansible.builtin.urn',)),
    'vault_encrypted': JinjaTest('ansible.builtin.vault_encrypted', 'vault_encrypted', 'ansible', ('ansible.builtin.vault_encrypted',)),
    'vaulted_file': JinjaTest('ansible.builtin.vaulted_file', 'vaulted_file', 'ansible', ('ansible.builtin.vaulted_file',)),
    'version': JinjaTest('ansible.builtin.version', 'version', 'ansible', ('ansible.builtin.version',)),
    'version_compare': JinjaTest('ansible.builtin.version_compare', 'version_compare', 'ansible', ('ansible.builtin.version_compare',)),
    '!=': JinjaTest('jinja2.!=', '!=', 'jinja2_builtin', ()),
    '<': JinjaTest('jinja2.<', '<', 'jinja2_builtin', ()),
    '<=': JinjaTest('jinja2.<=', '<=', 'jinja2_builtin', ()),
    '==': JinjaTest('jinja2.==', '==', 'jinja2_builtin', ()),
    '>': JinjaTest('jinja2.>', '>', 'jinja2_builtin', ()),
    '>=': JinjaTest('jinja2.>=', '>=', 'jinja2_builtin', ()),
    'boolean': JinjaTest('jinja2.boolean', 'boolean', 'jinja2_builtin', ()),
    'callable': JinjaTest('jinja2.callable', 'callable', 'jinja2_builtin', ()),
    'divisibleby': JinjaTest('jinja2.divisibleby', 'divisibleby', 'jinja2_builtin', ()),
    'eq': JinjaTest('jinja2.eq', 'eq', 'jinja2_builtin', ()),
    'equalto': JinjaTest('jinja2.equalto', 'equalto', 'jinja2_builtin', ()),
    'escaped': JinjaTest('jinja2.escaped', 'escaped', 'jinja2_builtin', ()),
    'even': JinjaTest('jinja2.even', 'even', 'jinja2_builtin', ()),
    'false': JinjaTest('jinja2.false', 'false', 'jinja2_builtin', ()),
    'filter': JinjaTest('jinja2.filter', 'filter', 'jinja2_builtin', ()),
    'float': JinjaTest('jinja2.float', 'float', 'jinja2_builtin', ()),
    'ge': JinjaTest('jinja2.ge', 'ge', 'jinja2_builtin', ()),
    'greaterthan': JinjaTest('jinja2.greaterthan', 'greaterthan', 'jinja2_builtin', ()),
    'gt': JinjaTest('jinja2.gt', 'gt', 'jinja2_builtin', ()),
    'in': JinjaTest('jinja2.in', 'in', 'jinja2_builtin', ()),
    'integer': JinjaTest('jinja2.integer', 'integer', 'jinja2_builtin', ()),
    'iterable': JinjaTest('jinja2.iterable', 'iterable', 'jinja2_builtin', ()),
    'le': JinjaTest('jinja2.le', 'le', 'jinja2_builtin', ()),
    'lessthan': JinjaTest('jinja2.lessthan', 'lessthan', 'jinja2_builtin', ()),
    'lower': JinjaTest('jinja2.lower', 'lower', 'jinja2_builtin', ()),
    'lt': JinjaTest('jinja2.lt', 'lt', 'jinja2_builtin', ()),
    'mapping': JinjaTest('jinja2.mapping', 'mapping', 'jinja2_builtin', ()),
    'ne': JinjaTest('jinja2.ne', 'ne', 'jinja2_builtin', ()),
    'none': JinjaTest('jinja2.none', 'none', 'jinja2_builtin', ()),
    'number': JinjaTest('jinja2.number', 'number', 'jinja2_builtin', ()),
    'odd': JinjaTest('jinja2.odd', 'odd', 'jinja2_builtin', ()),
    'sameas': JinjaTest('jinja2.sameas', 'sameas', 'jinja2_builtin', ()),
    'sequence': JinjaTest('jinja2.sequence', 'sequence', 'jinja2_builtin', ()),
    'string': JinjaTest('jinja2.string', 'string', 'jinja2_builtin', ()),
    'test': JinjaTest('jinja2.test', 'test', 'jinja2_builtin', ()),
    'true': JinjaTest('jinja2.true', 'true', 'jinja2_builtin', ()),
    'upper': JinjaTest('jinja2.upper', 'upper', 'jinja2_builtin', ()),
}

FILTER_NAMES: frozenset[str] = frozenset(FILTERS.keys())
TEST_NAMES: frozenset[str] = frozenset(TESTS.keys())


def is_valid_filter(name: str) -> bool:
    return name in FILTER_NAMES


def is_valid_test(name: str) -> bool:
    return name in TEST_NAMES
